### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Kevin-Andrew** [petrsnd/OtpCore#11]
The `while` loop at https://github.com/petrsnd/OtpCore/blob/release-1.0/OtpCore/Utilities.cs#L31 will be infinite if `counter` is ever a negative number, which is allowed and implied by the use of the signed data type, `long`.

**Comment by petrsnd** [comment]
Using a signed integer wasn't an arbitrary decision.  The HOTP spec talks about treating the counter as a 31-bit unsigned integer and masking out the sign bit.  https://www.ietf.org/rfc/rfc4226.txt.  See 5.3 and 5.4.  The author's justification was about modulo arithmetic differences depending on platform.  I followed the spec but should have been more careful about validating inputs.

TOTP starts to deal with larger counter sizes due to the calculation of the counter based on seconds from epoch.  That is why I moved from int to long.  The test vectors include 64bit values.  https://www.ietf.org/rfc/rfc6238.txt.

Anyway, the easiest fix is just to change the condition to > rather than != and throw an argument exception, because the algorithm is expecting a positive value.

**Comment by Kevin-Andrew** [comment]
You said:
> The HOTP spec talks about treating the counter as a 31-bit unsigned integer


When actually, the RFC says:
![image](https://user-images.githubusercontent.com/22459191/211871465-dd7cabd7-112f-4f6d-8d7c-9d0fadc642d3.png)


Then, later on, when describing the details of what happens **inside** the algorithm:

![image](https://user-images.githubusercontent.com/22459191/211872985-6bab884d-862a-4bf0-9b06-af921ea71002.png)

We see in other implementations, like https://github.com/gokyle/hotp/blob/master/hotpgen/hotpgen.go, lines [77](https://github.com/gokyle/hotp/blob/master/hotp.go#L77), [88](https://github.com/gokyle/hotp/blob/master/hotp.go#L88), even line [170](https://github.com/gokyle/hotp/blob/master/hotp.go#L170) from the URL parsing, treating the `counter` as an 8-byte unsigned integer. The class also supports allowing a `counter` value to be randomly generated. And [in this Java implementation](https://github.com/jchambers/java-otp/blob/java-otp-0.4.0/src/main/java/com/eatthepath/otp/HmacOneTimePasswordGenerator.java#L132), it takes in a signed `long` as the `counter` and works just fine if the value is negative. It doesn't throw an exception if the `counter` value is negative.

So I disagree with your statement of:
> ...because the algorithm is expecting a positive value.

**Your implementation** may have been written expecting a positive value, but nothing in [RFC 4226](https://www.rfc-editor.org/rfc/rfc4226) says that.

It's your project, but I'd be against throwing an exception if a negative value is provided as input, because that would make your project/implementation different from several others. You could consider changing the input parameter to a `ulong`, or perhaps just a `byte[]` and limit it to 8-bytes. To me, either of those would be acceptable, assuming the value can then be incremented consistently between this and the device. And what other changes may be needed if going that route, I don't know.

Or maybe, the entire method may be able to be written as the following, leaving the `long` datatype, and maybe nothing else has to change:
```
public static byte[] CounterToBuffer(long counter)
{
    // We only ever expect to run on a little-endian platform, so we need to reverse the bytes to big-endian, as specified:
    // https://www.rfc-editor.org/rfc/rfc4226#section-5.2
    // "The Key (K), the Counter (C), and Data values are hashed high-order byte first."
    return BitConverter.GetBytes(counter).Reverse().ToArray();
}
```

**Comment by petrsnd** [comment]
Yeah. I see your point. I'm hesitant to go to ulong and change the signature of the function. That would cause callers to have to change their code. I'd rather just give one bit away since 99 times out of one hundred this will be for totp and not hotp, and we will all be long dead before that period-based counters get that high.

**Comment by petrsnd** [comment]
Fixed.  See PR #12 for details.
